export default {
    zh: {
        hello: '你好',
        lang: '中文',
        title: '欧卡三屏 Multimon Config 生成器（兼容相同尺寸的双屏方案）',
        desp: "本计算方式由帖子 https://tieba.baidu.com/p/5725691718 提供，本工具主要是按照原作者的计算方法来实现。",
        about: "生成文件使用方法",
        btn1: '单个显示器的宽度',
        btn2: '单个显示器的高度',
        btn3: '人眼到中间显示器的距离',
        btn4: '边框宽度',
        btn5: '显示器夹角',
        danwei: '毫米/mm',
        btn3desp: '此数值（毫米）对视场（FOV）的影响较大，可根据实际情况调整。',
        btn4desp: '边框宽度（毫米）可以填负数。例如，三屏边框消除套件通常在这里填负数，或者填0等，可根据需要调整。',
        btn5desp: '一般来说，120度的三屏夹角就填60度，但可以根据实际情况进行微调。',
        createbtn1: '生成三屏配置',
        createbtn2: '生成双屏配置（第二块屏在右侧）',
        createbtn3: '生成双屏配置（第二块屏在左侧）',
        createToast: '生成成功并已复制',
        inputNotFull: '请输入完整信息',
        returnText: '返回',
        useDesp: {
            p1: '说明：用于计算《欧卡2》三屏参数，仅针对相同尺寸和分辨率的三台/两台显示器。',
            p2: '1. 用记事本打开 &lt;文档&gt;\Euro Truck Simulator 2\config.cfg 文件。',
            p3: '2. 将 r_multimon_mode 改为 4，g_console 改为 1，g_developer 改为 1，然后保存。',
            p4: '3. 在显卡驱动中设置三屏(双屏)连成一个屏幕。',
            p5: '4. 启动游戏，设置分辨率为最大，进入驾驶界面，按 ~ 键（主键盘 1 键左边）打开控制台。',
            p6: '5. 输入命令 multimon init three 回车，载入预设的三屏模式，然后输入命令 multimon save 保存设置。',
            p7: '6. 使用 Alt+Tab 切出游戏，打开 &lt;文档&gt;\Euro Truck Simulator 2\multimon_config.sii 文件。',
            p8: '7. 将生成的内容全选并覆盖现有的 multimon_config.sii 文件。',
            p9: '8. 使用 Alt+Tab 切回游戏，进入控制台输入命令 multimon reload 重载设置，完成。(如果不生效，重启游戏)'
        }
    },
    en: {
        hello: 'hello',
        lang: 'English',
        title: 'Euro Truck Simulator 2 Three-Screen Multimon Config Generator (Compatible with the Same Size Dual-Screen Setup)',
        desp: "This calculation method is provided by the post https://tieba.baidu.com/p/5725691718. This tool mainly implements the original author's calculation method.",
        about: "How to Use the Generated File",
        btn1: 'Single Monitor Width',
        btn2: 'Single Monitor Height',
        btn3: 'Distance from Eye to Center Monitor',
        btn4: 'Border Width',
        btn5: 'Screen Border Angle',
        danwei: 'mm',
        btn3desp: 'This value (mm) significantly affects the field of view (FOV), so adjust this value according to your situation.',
        btn4desp: 'The border width (mm) can be set to a negative number if you have a border elimination kit for three screens. Usually, negative values or 0 can be used according to your needs.',
        btn5desp: 'Typically, for a 120-degree screen angle, enter 60 degrees. However, you can adjust this based on your actual situation.',
        createbtn1: 'Generate Three-Screen Configuration',
        createbtn2: 'Generate Dual-Screen Configuration (Second Screen on the Right)',
        createbtn3: 'Generate Dual-Screen Configuration (Second Screen on the Left)',
        createToast: 'Generation successful and copied',
        inputNotFull: 'Please enter all information',
        returnText: 'Return',
        useDesp: {
            p1: 'Instructions: Used to calculate the three-screen parameters for Euro Truck Simulator 2, applicable only to three（two） monitors of the same size and resolution.',
            p2: '1. Open the <Documents>\Euro Truck Simulator 2\config.cfg file with Notepad.',
            p3: '2. Set r_multimon_mode to 4, g_console to 1, and g_developer to 1, then save the file.',
            p4: '3. Configure the graphics card driver to set up the three（two） screens as a single display.',
            p5: '4. Launch the game, set the resolution to the maximum, and enter the driving interface. Press the ~ key (located to the left of the number 1 key on the main keyboard) to open the console.',
            p6: '5. Enter the command multimon init three and press Enter to load the preset three-screen mode. Then enter multimon save to save the settings.',
            p7: '6. Alt+Tab out of the game and open <Documents>\Euro Truck Simulator 2\multimon_config.sii with a text editor.',
            p8: '7. Select all the generated content and replace the existing multimon_config.sii file with it.',
            p9: '8. Alt+Tab back into the game, enter the console, and type multimon reload to reload the settings. Done.（If it does not work, restart the game）'
        }
    },
    ja: {
        hello: 'こんにちは',
        lang: '日本語',
        title: 'Euro Truck Simulator 2三画面Multimon Configジェネレーター（同じサイズのデュアルスクリーンソリューションと互換性あり）',
        desp: "この計算方法は、投稿 https://tieba.baidu.com/p/5725691718 に提供されています。このツールは、元の著者の計算方法を実装しています。",
        about: "ファイル生成の使用方法",
        btn1: '単一モニターの幅',
        btn2: '単一モニターの高さ',
        btn3: '目から中央のモニターまでの距離',
        btn4: 'ボーダー幅',
        btn5: 'モニターの角度',
        danwei: 'ミリ/mm',
        btn3desp: 'この値（ミリメートル）はFOVに大きな影響を与えるので、実際の状況に応じて調整してください。',
        btn4desp: 'ボーダー幅（ミリメートル）は負の値を入力することができます。例えば、三画面用のボーダー消去キットがある場合、ここに負の値や0などを入力して自由に調整できます。',
        btn5desp: '一般的に、120度の三画面の角度は60と入力しますが、実際の状況に応じて調整することもできます。',
        createbtn1: '設定を生成してコピー',
        createbtn2: 'デュアルスクリーン設定を生成（2番目のスクリーンが右側）',
        createbtn3: 'デュアルスクリーン設定を生成（2番目のスクリーンが左側）',
        createToast: '生成してコピー成功',
        inputNotFull: '全ての情報を入力してください',
        returnText: '戻る',
        useDesp: {
            p1: '説明：Euro Truck Simulator 2の三画面パラメーターを計算するためのもので、同じサイズと解像度の三台のモニターにのみ対応しています。',
            p2: '1. メモ帳で <ドキュメント>\Euro Truck Simulator 2\config.cfg ファイルを開きます。',
            p3: '2. r_multimon_mode を 4 に、g_console を 1 に、g_developer を 1 に設定し、ファイルを保存します。',
            p4: '3. グラフィックカードドライバーで三画面を一つの画面として設定します。',
            p5: '4. ゲームを起動し、解像度を最大に設定し、運転画面に入ります。~キー（メインキーボードの1キーの左側）を押してコンソールを開きます。',
            p6: '5. コマンド multimon init three を入力してEnterキーを押し、プリセットの三画面モードを読み込みます。その後、コマンド multimon save を入力して設定を保存します。',
            p7: '6. Alt+Tabでゲームを外し、<ドキュメント>\Euro Truck Simulator 2\multimon_config.sii をテキストエディタで開きます。',
            p8: '7. 生成された内容を全て選択し、既存の multimon_config.sii ファイルと置き換えます。',
            p9: '8. Alt+Tabでゲームに戻り、コンソールで multimon reload と入力して設定をリロードします。完了です。'
        }
    },
    ko: {
        hello: '안녕하세요',
        lang: '한국어',
        title: 'Euro Truck Simulator 2 삼 화면 Multimon Config 생성기 (동일한 크기의 듀얼 스크린 솔루션과 호환됨)',
        desp: "이 계산 방법은 게시물 https://tieba.baidu.com/p/5725691718 에서 제공됩니다. 이 도구는 원 저자의 계산 방법을 구현한 것입니다.",
        about: "파일 생성 방법",
        btn1: '단일 모니터 너비',
        btn2: '단일 모니터 높이',
        btn3: '눈과 중앙 모니터까지의 거리',
        btn4: '테두리 너비',
        btn5: '모니터 각도',
        danwei: '밀리미터/mm',
        btn3desp: '이 값(밀리미터)은 FOV에 큰 영향을 미치므로 실제 상황에 따라 조정하는 것이 좋습니다.',
        btn4desp: '테두리 너비(밀리미터)는 음수로 입력할 수 있습니다. 예를 들어, 삼 화면 테두리 제거 키트가 있는 경우, 여기서 음수나 0 등을 입력하여 자유롭게 조정할 수 있습니다.',
        btn5desp: '일반적으로, 120도의 삼 화면 각도는 60으로 입력하지만, 실제 상황에 따라 조정할 수 있습니다.',
        createbtn1: '구성 생성 및 복사',
        createbtn2: '듀얼 스크린 구성 생성 (두 번째 화면이 오른쪽)',
        createbtn3: '듀얼 스크린 구성 생성 (두 번째 화면이 왼쪽)',
        createToast: '생성 성공 및 복사됨',
        inputNotFull: '모든 정보를 입력해 주세요',
        returnText: '돌아가기',
        useDesp: {
            p1: '설명: Euro Truck Simulator 2의 삼 화면 매개변수를 계산하는 데 사용되며, 동일한 크기와 해상도의 세 대 모니터에만 적용됩니다.',
            p2: '1. 메모장으로 <문서>\Euro Truck Simulator 2\config.cfg 파일을 엽니다.',
            p3: '2. r_multimon_mode를 4로, g_console을 1로, g_developer를 1로 설정한 후 파일을 저장합니다.',
            p4: '3. 그래픽 카드 드라이버에서 세 화면을 하나의 화면으로 설정합니다.',
            p5: '4. 게임을 시작하고 해상도를 최대화한 후 운전 화면으로 들어갑니다. ~ 키(주 키보드의 1번 키 왼쪽)를 눌러 콘솔을 엽니다.',
            p6: '5. 명령어 multimon init three를 입력하고 Enter를 눌러 삼 화면 모드를 로드합니다. 그런 다음 명령어 multimon save를 입력하여 설정을 저장합니다.',
            p7: '6. Alt+Tab으로 게임을 최소화하고 <문서>\Euro Truck Simulator 2\multimon_config.sii 파일을 텍스트 편집기로 엽니다.',
            p8: '7. 생성된 내용을 모두 선택하여 기존 multimon_config.sii 파일을 덮어씁니다.',
            p9: '8. Alt+Tab으로 게임에 다시 들어가 콘솔에 multimon reload를 입력하여 설정을 다시 로드합니다. 완료되었습니다.'
        }
    }
};
